import FormProduct from '@components/FormProduct';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import endPoints from '@services/api';
import axios from 'axios';
import Head from 'next/head';

export default function Edit() {
  const [product, setProduct] = useState({});
  const [notFound, setNotFound] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const { id } = router.query;
    if (!router.isReady) return;
    async function getProduct() {
      try {
        const response = await axios.get(endPoints.products.getProduct(id));
        if (response) {
          setProduct(response.data);
        }
      } catch (error) {
        console.error(error);
        setNotFound(true);
      }
    }
    getProduct();
  }, [router?.isReady]);

  return (
    <>
      <Head>
        <title>Edit Product: {product.title} - React Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {notFound ? <div className="text-center text-lg font-medium">Product Not Found</div> : <FormProduct product={product} />}
    </>
  );
}
